
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.6.0
 * Query Engine version: 75cbdc1eb7150937890ad5465d861175c6624711
 */
Prisma.prismaVersion = {
  client: "7.6.0",
  engine: "75cbdc1eb7150937890ad5465d861175c6624711"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.TenantScalarFieldEnum = {
  id: 'id',
  name: 'name',
  domain: 'domain',
  plan: 'plan',
  settings: 'settings',
  created_at: 'created_at'
};

exports.Prisma.ReceiptTemplateScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  name: 'name',
  settings: 'settings',
  created_at: 'created_at',
  branch_id: 'branch_id'
};

exports.Prisma.BranchScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  name: 'name',
  address: 'address',
  created_at: 'created_at',
  settings: 'settings'
};

exports.Prisma.RoleScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  permissions: 'permissions'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  phone: 'phone',
  email: 'email',
  password_hash: 'password_hash',
  role_id: 'role_id',
  is_active: 'is_active',
  created_at: 'created_at',
  first_name: 'first_name',
  last_name: 'last_name',
  gender: 'gender',
  photo_url: 'photo_url'
};

exports.Prisma.TeacherScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  user_id: 'user_id',
  branch_id: 'branch_id',
  specialization: 'specialization',
  salary_type: 'salary_type',
  salary_amount: 'salary_amount',
  joined_at: 'joined_at',
  date_of_birth: 'date_of_birth',
  description: 'description',
  archive_reason: 'archive_reason',
  archived_at: 'archived_at',
  is_archived: 'is_archived',
  type: 'type'
};

exports.Prisma.TeacherAttendanceScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  teacher_id: 'teacher_id',
  schedule_id: 'schedule_id',
  date: 'date',
  status: 'status',
  late_minutes: 'late_minutes',
  note: 'note',
  created_at: 'created_at'
};

exports.Prisma.StaffAttendanceScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  staff_id: 'staff_id',
  branch_id: 'branch_id',
  date: 'date',
  status: 'status',
  delay_time: 'delay_time',
  note: 'note',
  created_at: 'created_at'
};

exports.Prisma.TeacherPerformanceScalarFieldEnum = {
  id: 'id',
  teacher_id: 'teacher_id',
  grading_timeliness: 'grading_timeliness',
  avg_grade: 'avg_grade',
  attendance_rate: 'attendance_rate',
  last_updated: 'last_updated'
};

exports.Prisma.TeacherFeedbackScalarFieldEnum = {
  id: 'id',
  teacher_id: 'teacher_id',
  student_id: 'student_id',
  rating: 'rating',
  comment: 'comment',
  created_at: 'created_at'
};

exports.Prisma.TeacherArchiveReasonScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  name: 'name',
  created_at: 'created_at'
};

exports.Prisma.TeacherSpecializationScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  name: 'name',
  created_at: 'created_at'
};

exports.Prisma.StaffScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  user_id: 'user_id',
  branch_id: 'branch_id',
  position: 'position',
  salary: 'salary',
  archive_reason: 'archive_reason',
  archived_at: 'archived_at',
  is_archived: 'is_archived'
};

exports.Prisma.StudentScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  user_id: 'user_id',
  status: 'status',
  parent_id: 'parent_id',
  joined_at: 'joined_at',
  balance: 'balance',
  branch_id: 'branch_id',
  archive_reason: 'archive_reason',
  is_archived: 'is_archived',
  parent_phone: 'parent_phone',
  tags: 'tags',
  archived_at: 'archived_at',
  date_of_birth: 'date_of_birth',
  book_balance: 'book_balance',
  course_balance: 'course_balance',
  mock_balance: 'mock_balance',
  lead_id: 'lead_id',
  is_vip: 'is_vip'
};

exports.Prisma.LeadStageScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  name: 'name',
  color: 'color',
  order: 'order'
};

exports.Prisma.LeadSourceScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  name: 'name',
  slug: 'slug'
};

exports.Prisma.ArchiveReasonScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  name: 'name',
  created_at: 'created_at'
};

exports.Prisma.StudentArchiveReasonScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  name: 'name',
  created_at: 'created_at'
};

exports.Prisma.LeadScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  name: 'name',
  phone: 'phone',
  manager_id: 'manager_id',
  notes: 'notes',
  created_at: 'created_at',
  branch_id: 'branch_id',
  source_id: 'source_id',
  stage_id: 'stage_id',
  archive_reason: 'archive_reason',
  status: 'status',
  converted_at: 'converted_at'
};

exports.Prisma.CrmTaskScalarFieldEnum = {
  id: 'id',
  lead_id: 'lead_id',
  manager_id: 'manager_id',
  title: 'title',
  deadline: 'deadline',
  status: 'status',
  created_at: 'created_at'
};

exports.Prisma.CourseScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  name: 'name',
  description: 'description',
  branch_id: 'branch_id'
};

exports.Prisma.GroupScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  course_id: 'course_id',
  teacher_id: 'teacher_id',
  room_id: 'room_id',
  name: 'name',
  capacity: 'capacity',
  start_date: 'start_date',
  branch_id: 'branch_id',
  current_stage: 'current_stage',
  end_date: 'end_date',
  last_stage_at: 'last_stage_at',
  price: 'price',
  stage_duration_months: 'stage_duration_months',
  status: 'status',
  support_teacher_id: 'support_teacher_id',
  total_stages: 'total_stages',
  description: 'description',
  is_online: 'is_online',
  main_teacher_days: 'main_teacher_days',
  support_teacher_days: 'support_teacher_days',
  telegram_chat_id: 'telegram_chat_id',
  archive_reason: 'archive_reason',
  archived_at: 'archived_at',
  is_archived: 'is_archived',
  is_vip: 'is_vip',
  teacher_salary_type: 'teacher_salary_type',
  teacher_salary_value: 'teacher_salary_value',
  support_salary_type: 'support_salary_type',
  support_salary_value: 'support_salary_value'
};

exports.Prisma.RoomScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  branch_id: 'branch_id',
  name: 'name',
  capacity: 'capacity',
  description: 'description',
  created_at: 'created_at',
  is_active: 'is_active'
};

exports.Prisma.EnrollmentScalarFieldEnum = {
  id: 'id',
  student_id: 'student_id',
  group_id: 'group_id',
  enrolled_at: 'enrolled_at',
  status: 'status'
};

exports.Prisma.ScheduleScalarFieldEnum = {
  id: 'id',
  group_id: 'group_id',
  day_of_week: 'day_of_week',
  start_time: 'start_time',
  end_time: 'end_time',
  room_id: 'room_id'
};

exports.Prisma.AttendanceScalarFieldEnum = {
  id: 'id',
  enrollment_id: 'enrollment_id',
  schedule_id: 'schedule_id',
  date: 'date',
  status: 'status',
  score: 'score',
  marked_by: 'marked_by',
  marked_at: 'marked_at'
};

exports.Prisma.CashboxScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  branch_id: 'branch_id',
  name: 'name',
  balance: 'balance',
  created_at: 'created_at',
  balance_other: 'balance_other',
  type: 'type'
};

exports.Prisma.CashflowTransferScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  branch_id: 'branch_id',
  source_id: 'source_id',
  destination_id: 'destination_id',
  amount_cash: 'amount_cash',
  amount_other: 'amount_other',
  type: 'type',
  description: 'description',
  created_at: 'created_at',
  created_by: 'created_by'
};

exports.Prisma.PaymentScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  student_id: 'student_id',
  amount: 'amount',
  type: 'type',
  cashier_id: 'cashier_id',
  created_at: 'created_at',
  branch_id: 'branch_id',
  cashbox_id: 'cashbox_id',
  description: 'description',
  external_id: 'external_id',
  group_id: 'group_id',
  status: 'status',
  archive_reason: 'archive_reason',
  archived_at: 'archived_at',
  is_archived: 'is_archived',
  invoice_id: 'invoice_id',
  paid_for_month: 'paid_for_month',
  category_id: 'category_id'
};

exports.Prisma.PaymentCategoryScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  branch_id: 'branch_id',
  name: 'name',
  is_active: 'is_active',
  created_at: 'created_at'
};

exports.Prisma.InvoiceScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  branch_id: 'branch_id',
  student_id: 'student_id',
  group_id: 'group_id',
  amount: 'amount',
  paid_amount: 'paid_amount',
  status: 'status',
  type: 'type',
  month: 'month',
  created_at: 'created_at',
  start_date: 'start_date',
  end_date: 'end_date'
};

exports.Prisma.ExpenseScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  amount: 'amount',
  category: 'category',
  description: 'description',
  date: 'date',
  created_by: 'created_by',
  branch_id: 'branch_id',
  cashbox_id: 'cashbox_id',
  archive_reason: 'archive_reason',
  archived_at: 'archived_at',
  category_id: 'category_id',
  department_id: 'department_id',
  is_archived: 'is_archived',
  payment_method: 'payment_method',
  responsible_id: 'responsible_id',
  source_type: 'source_type',
  staff_id: 'staff_id',
  type: 'type'
};

exports.Prisma.DepartmentScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  name: 'name'
};

exports.Prisma.ExpenseCategoryScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  name: 'name',
  is_active: 'is_active'
};

exports.Prisma.ExpensePlanScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  branch_id: 'branch_id',
  category_id: 'category_id',
  amount: 'amount',
  date: 'date',
  description: 'description',
  created_at: 'created_at'
};

exports.Prisma.TransactionScalarFieldEnum = {
  id: 'id',
  payment_id: 'payment_id',
  amount: 'amount',
  balance_before: 'balance_before',
  balance_after: 'balance_after',
  created_at: 'created_at'
};

exports.Prisma.PayrollScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  teacher_id: 'teacher_id',
  amount: 'amount',
  period: 'period',
  status: 'status',
  paid_at: 'paid_at',
  created_at: 'created_at',
  bonus: 'bonus',
  branch_id: 'branch_id',
  deduction: 'deduction',
  staff_id: 'staff_id',
  archive_reason: 'archive_reason',
  archived_at: 'archived_at',
  cashbox_id: 'cashbox_id',
  description: 'description',
  is_archived: 'is_archived',
  payment_method: 'payment_method',
  type: 'type',
  group_id: 'group_id'
};

exports.Prisma.ExamScalarFieldEnum = {
  id: 'id',
  group_id: 'group_id',
  title: 'title',
  date: 'date',
  max_score: 'max_score'
};

exports.Prisma.GradeScalarFieldEnum = {
  id: 'id',
  exam_id: 'exam_id',
  student_id: 'student_id',
  score: 'score',
  feedback: 'feedback',
  created_at: 'created_at'
};

exports.Prisma.AssignmentScalarFieldEnum = {
  id: 'id',
  group_id: 'group_id',
  title: 'title',
  deadline: 'deadline',
  max_score: 'max_score'
};

exports.Prisma.SubmissionScalarFieldEnum = {
  id: 'id',
  assignment_id: 'assignment_id',
  student_id: 'student_id',
  score: 'score',
  submitted_at: 'submitted_at',
  feedback: 'feedback'
};

exports.Prisma.DiscountScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  name: 'name',
  type: 'type',
  value: 'value',
  is_active: 'is_active',
  created_at: 'created_at'
};

exports.Prisma.StudentDiscountScalarFieldEnum = {
  id: 'id',
  student_id: 'student_id',
  discount_id: 'discount_id',
  granted_at: 'granted_at',
  expires_at: 'expires_at'
};

exports.Prisma.NotificationScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  type: 'type',
  channel: 'channel',
  recipient_id: 'recipient_id',
  status: 'status',
  sent_at: 'sent_at',
  created_at: 'created_at'
};

exports.Prisma.ProductCategoryScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  name: 'name',
  created_at: 'created_at'
};

exports.Prisma.ProductScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  branch_id: 'branch_id',
  category_id: 'category_id',
  name: 'name',
  stock: 'stock',
  price: 'price',
  cost_price: 'cost_price',
  is_for_sale: 'is_for_sale',
  is_top: 'is_top',
  photo_url: 'photo_url',
  created_at: 'created_at'
};

exports.Prisma.CustomerScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  branch_id: 'branch_id',
  name: 'name',
  phone: 'phone',
  created_at: 'created_at'
};

exports.Prisma.SaleTransactionScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  branch_id: 'branch_id',
  amount: 'amount',
  payment_method: 'payment_method',
  student_id: 'student_id',
  customer_id: 'customer_id',
  staff_id: 'staff_id',
  cashbox_id: 'cashbox_id',
  status: 'status',
  description: 'description',
  created_at: 'created_at',
  archive_reason: 'archive_reason',
  archived_at: 'archived_at',
  is_archived: 'is_archived'
};

exports.Prisma.SaleItemScalarFieldEnum = {
  id: 'id',
  sale_id: 'sale_id',
  product_id: 'product_id',
  quantity: 'quantity',
  price_at_sale: 'price_at_sale'
};

exports.Prisma.BonusSourceScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  name: 'name',
  is_active: 'is_active'
};

exports.Prisma.BonusScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  branch_id: 'branch_id',
  teacher_id: 'teacher_id',
  staff_id: 'staff_id',
  amount: 'amount',
  reason: 'reason',
  source_id: 'source_id',
  date: 'date',
  payment_method: 'payment_method',
  cashbox_id: 'cashbox_id',
  created_at: 'created_at',
  is_archived: 'is_archived',
  archive_reason: 'archive_reason',
  archived_at: 'archived_at'
};

exports.Prisma.SmsTemplateScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  branch_id: 'branch_id',
  name: 'name',
  text: 'text',
  is_active: 'is_active',
  created_at: 'created_at'
};

exports.Prisma.AutoSmsConfigScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  branch_id: 'branch_id',
  template_id: 'template_id',
  type: 'type',
  scheduled_day: 'scheduled_day',
  scheduled_time: 'scheduled_time',
  is_enabled: 'is_enabled',
  created_at: 'created_at'
};

exports.Prisma.PenaltyScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  teacher_id: 'teacher_id',
  group_id: 'group_id',
  schedule_id: 'schedule_id',
  amount: 'amount',
  reason: 'reason',
  date: 'date',
  is_automated: 'is_automated',
  created_at: 'created_at',
  branch_id: 'branch_id'
};

exports.Prisma.SmsLogScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  branch_id: 'branch_id',
  phone: 'phone',
  message: 'message',
  status: 'status',
  sent_at: 'sent_at'
};

exports.Prisma.RevenueSegmentScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  branch_id: 'branch_id',
  payment_id: 'payment_id',
  amount: 'amount',
  date: 'date',
  group_id: 'group_id',
  type: 'type',
  created_at: 'created_at'
};

exports.Prisma.PayrollSegmentScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  branch_id: 'branch_id',
  payroll_id: 'payroll_id',
  amount: 'amount',
  date: 'date',
  created_at: 'created_at'
};

exports.Prisma.CallCenterTaskScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  branch_id: 'branch_id',
  student_id: 'student_id',
  staff_id: 'staff_id',
  type: 'type',
  status: 'status',
  last_call_at: 'last_call_at',
  next_call_at: 'next_call_at',
  promised_date: 'promised_date',
  note: 'note',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.StudentStatus = exports.$Enums.StudentStatus = {
  LEAD: 'LEAD',
  TRIAL: 'TRIAL',
  ACTIVE: 'ACTIVE',
  FROZEN: 'FROZEN',
  DEBTOR: 'DEBTOR',
  GRADUATED: 'GRADUATED',
  REMOVED: 'REMOVED'
};

exports.Prisma.ModelName = {
  Tenant: 'Tenant',
  ReceiptTemplate: 'ReceiptTemplate',
  Branch: 'Branch',
  Role: 'Role',
  User: 'User',
  Teacher: 'Teacher',
  TeacherAttendance: 'TeacherAttendance',
  StaffAttendance: 'StaffAttendance',
  TeacherPerformance: 'TeacherPerformance',
  TeacherFeedback: 'TeacherFeedback',
  TeacherArchiveReason: 'TeacherArchiveReason',
  TeacherSpecialization: 'TeacherSpecialization',
  Staff: 'Staff',
  Student: 'Student',
  LeadStage: 'LeadStage',
  LeadSource: 'LeadSource',
  ArchiveReason: 'ArchiveReason',
  StudentArchiveReason: 'StudentArchiveReason',
  Lead: 'Lead',
  CrmTask: 'CrmTask',
  Course: 'Course',
  Group: 'Group',
  Room: 'Room',
  Enrollment: 'Enrollment',
  Schedule: 'Schedule',
  Attendance: 'Attendance',
  Cashbox: 'Cashbox',
  CashflowTransfer: 'CashflowTransfer',
  Payment: 'Payment',
  PaymentCategory: 'PaymentCategory',
  Invoice: 'Invoice',
  Expense: 'Expense',
  Department: 'Department',
  ExpenseCategory: 'ExpenseCategory',
  ExpensePlan: 'ExpensePlan',
  Transaction: 'Transaction',
  Payroll: 'Payroll',
  Exam: 'Exam',
  Grade: 'Grade',
  Assignment: 'Assignment',
  Submission: 'Submission',
  Discount: 'Discount',
  StudentDiscount: 'StudentDiscount',
  Notification: 'Notification',
  ProductCategory: 'ProductCategory',
  Product: 'Product',
  Customer: 'Customer',
  SaleTransaction: 'SaleTransaction',
  SaleItem: 'SaleItem',
  BonusSource: 'BonusSource',
  Bonus: 'Bonus',
  SmsTemplate: 'SmsTemplate',
  AutoSmsConfig: 'AutoSmsConfig',
  Penalty: 'Penalty',
  SmsLog: 'SmsLog',
  RevenueSegment: 'RevenueSegment',
  PayrollSegment: 'PayrollSegment',
  CallCenterTask: 'CallCenterTask'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
